// ------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本: 16.0.0.0
//  
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.Templates
{
    using System.Linq;
    using CodeGenerator.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\EnumTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class EnumTemplate : CodeGenerator.Templates.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 4 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\EnumTemplate.tt"
 
	ColumnMeta enumMeta = TableMeta.Columns[0];

	FilePath = TableMeta.NameSpace + "/Enums/" + enumMeta.Name + ".cs";

            
            #line default
            #line hidden
            this.Write("using System.ComponentModel.DataAnnotations;\r\n\r\nnamespace ");
            
            #line 11 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Enums \r\n{\r\n\t/// <summary>");
            
            #line 13 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumMeta.Description));
            
            #line default
            #line hidden
            this.Write("</summary>\r\n\tpublic enum ");
            
            #line 14 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumMeta.Name));
            
            #line default
            #line hidden
            this.Write(" \r\n\t{\r\n\t\t//TODO 程式產生未完成\r\n\t\t");
            
            #line 17 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\EnumTemplate.tt"
 foreach(var item in enumMeta.EnumList) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t/// <summary>");
            
            #line 19 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item));
            
            #line default
            #line hidden
            this.Write("</summary>\r\n\t\t[Display(Name = \"");
            
            #line 20 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item));
            
            #line default
            #line hidden
            this.Write("\")]\r\n\t\t");
            
            #line 21 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\EnumTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item));
            
            #line default
            #line hidden
            this.Write(",\r\n\t\t");
            
            #line 22 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\EnumTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t}\r\n\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
