// ------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本: 16.0.0.0
//  
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.Templates.Mvc
{
    using CodeGenerator.Models;
    using System.Linq;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\DialogViewTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class DialogViewTemplate : CodeGenerator.Templates.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 5 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\DialogViewTemplate.tt"
 
	FilePath = TableMeta.NameSpace + ".WebApp/Views/" + TableMeta.Name + "/Dialog.cshtml";

            
            #line default
            #line hidden
            this.Write("@model ");
            
            #line 8 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\DialogViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("ViewModel\r\n\r\n\r\n@{\r\n\tLayout = \"~/Views/Shared/_DialogLayout.cshtml\";\r\n\r\n\tbool isCr" +
                    "eate = \"Create\".EqualsIgnoreCase(ViewContext.RouteData.GetRequiredString(\"action" +
                    "\"));\r\n\r\n\tViewBag.Title = isCreate ? \"新增");
            
            #line 16 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\DialogViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Description));
            
            #line default
            #line hidden
            this.Write("\" : \"編輯");
            
            #line 16 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\DialogViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Description));
            
            #line default
            #line hidden
            this.Write(@""";
}

@section Styles {
<style type=""text/css""></style>
}


@section Scripts {
<script type=""text/javascript"">
Dialog.resize(480, 360);

jQuery(function ($) {
});
</script>
}


@using (Html.BeginForm(null, null, FormMethod.Post, new
{
	action = """",
	@class = ""form-horizontal form-sm"",
	ext_one_submit = """",
	ext_exit_alert = ""資料尚未儲存，確定要離開？"",
}))
{
	@Html.HiddenFor(m => m.");
            
            #line 42 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\DialogViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\r\n\t<div class=\"modal-header\">\r\n\t\t<h4 class=\"modal-title\">@ViewBag.Title</h4>\r\n" +
                    "\t</div>\r\n\r\n\t<div class=\"modal-body auto\">\r\n    @{ var labelCol = \"col-sm-4\"; var" +
                    " wrapCol = \"col-sm-8\"; }\r\n\r\n");
            
            #line 51 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\DialogViewTemplate.tt"
 foreach(var col in ActiveColumns.Where(x => !x.IsPrimaryKey)) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t<div class=\"form-group\">\r\n\t\t\t@Html.BsLabelFor(m => m.");
            
            #line 54 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\DialogViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(", new { @class = labelCol + \"");
            
            #line 54 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\DialogViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((col.IsNullable ? "" : " required")));
            
            #line default
            #line hidden
            this.Write("\" })\r\n\t\t\t<div class=\"@wrapCol\">\r\n\t\t\t\t@Html.");
            
            #line 56 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\DialogViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.EditBox()));
            
            #line default
            #line hidden
            this.Write("(m => m.");
            
            #line 56 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\DialogViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t<span class=\"form-tip\">@Html.ValidationMessageFor(m => m.");
            
            #line 57 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\DialogViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(")</span>\r\n\t\t\t</div>\r\n\t\t</div>\r\n");
            
            #line 60 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\DialogViewTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"	</div>


	<div class=""modal-footer"">
		<span class=""btn btn-default btn-sm"" data-dismiss=""modal""><i class=""fa fa-times fa-lg""></i> 關閉</span>

		<button class=""btn btn-primary btn-sm"" type=""submit""><i class=""fa fa-save fa-lg""></i> 儲存</button>

		@if (!isCreate @*&& User.AnyAct(ACT.");
            
            #line 69 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\DialogViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Delete)*@ )\r\n\t\t{\r\n\t\t\t<button class=\"btn btn-danger btn-sm pull-left\" type=\"submit" +
                    "\" name=\"action\" value=\"delete\" onclick=\"return confirm(\'確定要刪除嗎?\');\">\r\n\t\t\t\t<i cla" +
                    "ss=\"fa fa-trash-o fa-lg\"></i> 刪除\r\n\t\t\t</button>\r\n\t\t}\r\n\t</div>\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
