// ------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本: 16.0.0.0
//  
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.Templates.Mvc
{
    using System.Linq;
    using CodeGenerator.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ListViewTemplate : CodeGenerator.Templates.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 4 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
 
	FilePath = TableMeta.NameSpace + ".WebApp/Views/" + TableMeta.Name + "/List.cshtml";

            
            #line default
            #line hidden
            this.Write("@{\r\n\tViewBag.Title = \"");
            
            #line 8 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Description));
            
            #line default
            #line hidden
            this.Write("列表\";\r\n\tstring tableListId = \"");
            
            #line 9 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("List\";\r\n\tPagination<");
            
            #line 10 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write(@"Domain> pagination = ViewBag.Pagination;

}

@section Styles {
}


@section Scripts {
}


<div class=""page-header"" ext-horizontal-fix="""">
	<h1>@ViewBag.Title</h1>
</div>


@using (Html.BeginForm(null, null, FormMethod.Get, new { id = ""SearchForm"", @class = ""well btn-toolbar"", ext_horizontal_fix = """" }))
{
	/*if (User.AnyAct(ACT.");
            
            #line 29 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Create))\r\n\t{*/\r\n\t\t<div class=\"toolbar-left\">\r\n\t\t\t<a class=\"btn btn-success btn-sm" +
                    "\" href=\"@Url.Action(\"Create\")\"><i class=\"fa fa-plus fa-lg\"></i> 新增</a>\r\n\t\t</div>" +
                    "\r\n\t/*}*/\r\n\t<div class=\"toolbar-left\">\r\n\t\t@(Html.WhereBuilder(pagination)\r\n");
            
            #line 37 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
 foreach(var col in TableMeta.Columns.Where(x => !x.IsPrimaryKey)) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t.Column(x => x.");
            
            #line 38 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.WhereBox()));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 39 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"		)

	</div>

	<div class=""toolbar-left"">
		<button type=""submit"" class=""btn btn-primary btn-sm""><i class=""fa fa-search fa-lg""></i> 搜尋</button>
		<a class=""btn btn-default btn-sm hidden-xs hidden-sm"" href=""?Export=true&@Request.QueryString"" target=""_blank"">
			<i class=""fa fa-file-excel-o fa-lg""></i> 匯出
		</a>
	</div>

	<div class=""toolbar-left"">
		@Html.OrderableBtn(tableListId)
		@Html.SortBuilderBtn(tableListId)
	</div>

	@Html.PageSizeChange(pagination)
}



<div id=""@tableListId"">
	<table class=""table table-striped table-bordered table-condensed table-nowrap table-hover"">
		<thead ext-table-fix="""">
			<tr class=""head"">
				<th class=""min""></th>
");
            
            #line 66 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
 foreach(var col in TableMeta.Columns) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t<th ext-orderable-col=\"\" class=\"");
            
            #line 67 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("\">@pagination.PagerSortFor(x => x.");
            
            #line 67 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(")</th>\r\n");
            
            #line 68 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t</tr>\r\n\t\t</thead>\r\n\t\t<tbody dialog-change-reload=\"\">\r\n\t\t\t@foreach (var row in " +
                    "pagination.List)\r\n\t\t\t{\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<td class=\"min\">\r\n\t\t\t\t\t\t@*@if (User.AnyAc" +
                    "t(ACT.");
            
            #line 76 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Edit))\r\n\t\t\t\t\t\t{*@\r\n\t\t\t\t\t\t\t@{ string editUrl = Url.Action(\"Edit\", new { row.");
            
            #line 78 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Name));
            
            #line default
            #line hidden
            this.Write(" }); }\r\n\t\t\t\t\t\t\t<a class=\"btn btn-warning btn-sm btn-icon\" href=\"@editUrl\"><i clas" +
                    "s=\"fa fa-pencil fa-lg\"></i></a>\r\n\t\t\t\t\t\t@*}*@\r\n\t\t\t\t\t</td>\r\n");
            
            #line 82 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
 foreach(var col in TableMeta.Columns) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<td class=\"");
            
            #line 83 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("\">@");
            
            #line 83 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.DisplayBox("row")));
            
            #line default
            #line hidden
            this.Write("</td>\r\n");
            
            #line 84 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"				</tr>
			}
		</tbody>
	</table>

	@Html.PageEmptyAlert(pagination)
</div>


<div class=""text-center"" ext-horizontal-fix="""">
	<ul class=""pagination"">@Html.PagerLinks(pagination)</ul>
</div>







@section Export {
	@if (ViewBag.IsExport != true) { return; }

	@(Html.ExcelExport(pagination.List)
		
");
            
            #line 109 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
 foreach(var col in TableMeta.Columns) { 
            
            #line default
            #line hidden
            this.Write("\t\t.Column(row => ");
            
            #line 110 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.DisplayBox("row")));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 111 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t)\r\n\r\n\t \r\n @*\r\n\t@{\r\n\t\tstring thStyle = \"color: #fff; background: #2d6da3;\";\r\n\t}\r\n" +
                    "\t<table>\r\n\t\t<tr>\r\n");
            
            #line 121 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
 foreach(var col in TableMeta.Columns) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t<td style=\"@thStyle\">@pagination.DisplayNameFor(x => x.");
            
            #line 122 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(")</td>\r\n");
            
            #line 123 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t</tr>\r\n\t\t@foreach (var row in pagination.List)\r\n\t\t{\r\n\t\t\t<tr>\r\n");
            
            #line 128 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
 foreach(var col in TableMeta.Columns) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t<td>@");
            
            #line 129 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.DisplayBox("row")));
            
            #line default
            #line hidden
            this.Write("</td>\r\n");
            
            #line 130 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Mvc\ListViewTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t</tr>\r\n\t\t}\r\n\t</table>\r\n *@\r\n\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
