// ------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本: 16.0.0.0
//  
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.Templates.Wcf
{
    using System.Linq;
    using CodeGenerator.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\DomainTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class DomainTemplate : CodeGenerator.Templates.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 4 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\DomainTemplate.tt"
 
	string className = TableMeta.Name + "Domain";
	FilePath = TableMeta.NameSpace + "/" + className + ".cs";

            
            #line default
            #line hidden
            this.Write("using System;\r\nusing System.ComponentModel.DataAnnotations;\r\nusing JustWin.API.Mo" +
                    "dels;\r\nusing ");
            
            #line 11 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Domain.Enums;\r\n\r\n\r\nnamespace ");
            
            #line 14 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Domain \r\n{\r\n\t/// <summary>");
            
            #line 16 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Description));
            
            #line default
            #line hidden
            this.Write("</summary>\r\n\tpublic class ");
            
            #line 17 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(" \r\n\t{\r\n\t\t");
            
            #line 19 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\DomainTemplate.tt"
 foreach(var col in TableMeta.Columns) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t/// <summary>");
            
            #line 21 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Description));
            
            #line default
            #line hidden
            this.Write("</summary>\t\t\r\n\t\t[Display(Name = \"");
            
            #line 22 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.DisplayName));
            
            #line default
            #line hidden
            this.Write("\")]\r\n\t\tpublic ");
            
            #line 23 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CodeType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 23 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\DomainTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n\t\t");
            
            #line 24 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\DomainTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
