// ------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本: 16.0.0.0
//  
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.Templates.Wcf
{
    using System.Linq;
    using CodeGenerator.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\IDaoTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class IDaoTemplate : CodeGenerator.Templates.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 4 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\IDaoTemplate.tt"
 
	string className = "I" + TableMeta.Name + "Dao";
	FilePath = TableMeta.NameSpace + ".Dao/" + className + ".cs";

            
            #line default
            #line hidden
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing JustWin.API.Models;\r\nusin" +
                    "g ");
            
            #line 11 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Domain;\r\nusing ");
            
            #line 12 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Domain.Enums;\r\n\r\n\r\nnamespace ");
            
            #line 15 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Dao\r\n{\r\n\t/// <summary>");
            
            #line 17 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Description));
            
            #line default
            #line hidden
            this.Write("</summary>\r\n\tpublic interface ");
            
            #line 18 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\t//TODO 程式產生未完成\r\n\t\t//Dictionary<int, string> GetDic(string status = null);" +
                    "\r\n\r\n\t\t//TODO 程式產生未完成\r\n\t\t//Dictionary<string, string> GetStatusItems();\r\n\r\n\t\tPagi" +
                    "nation<");
            
            #line 26 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> GetPagination(WhereParams<");
            
            #line 26 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> findParam, PageParams<");
            
            #line 26 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> pageParams);\r\n\r\n\t\t//TODO 程式產生未完成\r\n\t\t//List<");
            
            #line 29 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> GetList(WhereParams<");
            
            #line 29 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain> findParam = null);\r\n\t\t\r\n\t\t");
            
            #line 31 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain GetById(");
            
            #line 31 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.CodeType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 31 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Variable));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\r\n\t\tint Save(");
            
            #line 33 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain domain);\r\n\t\t\t\t\r\n\t\tvoid Delete(");
            
            #line 35 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.CodeType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 35 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Variable));
            
            #line default
            #line hidden
            this.Write(", int modifyBy);\n\t\t\n\t\t//TODO 程式產生未完成\n\t\t//bool IsXxxDuplicate(");
            
            #line 35 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.CodeType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 35 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Wcf\IDaoTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.PK.Variable));
            
            #line default
            #line hidden
            this.Write(", string xxx);\n\r\n\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
