// ------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本: 16.0.0.0
//  
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.Templates.Test
{
    using System.Linq;
    using CodeGenerator.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Test\ServiceTestTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ServiceTestTemplate : CodeGenerator.Templates.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 4 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Test\ServiceTestTemplate.tt"
 
	string className = TableMeta.Name + "ServiceTests";
	FilePath = TableMeta.NameSpace + ".Tests/Service/Impl/" + className + ".cs";

            
            #line default
            #line hidden
            this.Write("using JustWin.API;\r\nusing Moq;\r\nusing System;\r\nusing System.Collections.Generic;\r" +
                    "\nusing System.Linq;\r\nusing System.Text;\r\nusing System.Threading.Tasks;\r\nusing ");
            
            #line 15 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Test\ServiceTestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Dao;\r\nusing ");
            
            #line 16 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Test\ServiceTestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Domain;\r\nusing ");
            
            #line 17 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Test\ServiceTestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Domain.Enums;\r\nusing Xunit;\r\n\r\nnamespace ");
            
            #line 20 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Test\ServiceTestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.NameSpace));
            
            #line default
            #line hidden
            this.Write(".Service.Impl.Tests\r\n{\r\n\tpublic class ");
            
            #line 22 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Test\ServiceTestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\r\n\t\tpublic static IEnumerable<object[]> Save_ValidationTest_Data\r\n\t\t{\r\n\t\t\tg" +
                    "et\r\n\t\t\t{\r\n\t\t\t\tyield return new object[] { new ");
            
            #line 29 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Test\ServiceTestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain(){\r\n\t\t\t\t//TODO 程式產生未完成\r\n");
            
            #line 31 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Test\ServiceTestTemplate.tt"
 foreach(var col in TableMeta.Columns) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t");
            
            #line 32 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Test\ServiceTestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = default(");
            
            #line 32 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Test\ServiceTestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CodeType));
            
            #line default
            #line hidden
            this.Write("),\r\n");
            
            #line 33 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Test\ServiceTestTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t}};\r\n\t\t\t}\r\n\t\t}\r\n\r\n\r\n\t\t[Theory]\r\n\t\t[MemberData(\"Save_ValidationTest_Data\")]\r\n\t" +
                    "\tpublic void Save_ValidationTest(");
            
            #line 41 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Test\ServiceTestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Domain domain)\r\n\t\t{\r\n\t\t\tvar mock = new Mock<I");
            
            #line 43 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Test\ServiceTestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Dao>();\r\n\t\t\tvar ");
            
            #line 44 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Test\ServiceTestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Variable));
            
            #line default
            #line hidden
            this.Write("Service = new ");
            
            #line 44 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Test\ServiceTestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Name));
            
            #line default
            #line hidden
            this.Write("Service(mock.Object);\r\n\t\t\tAssert.Throws<OrionException>(() => ");
            
            #line 45 "D:\Jax-Work\Dropbox\JW-Project\CoreTpl\CodeGenerator\Templates\Test\ServiceTestTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TableMeta.Variable));
            
            #line default
            #line hidden
            this.Write("Service.Save(domain));\r\n\t\t}\r\n\r\n\r\n\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
